#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 0.1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "aws-mfa-secure"
require "aws_mfa_secure/cli"

AwsMfaSecure::CLI.start(ARGV)
